version: "3"
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres_1
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: product_db
      POSTGRES_PASSOWORD: root
    restart: always
  app:
    image: spring-boot-product
    build: .
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://@db:5432/product_db
    restart: always
    depends_on:
      - db



